---
- name: "Building UP OSPF"
  hosts: arista
  vars:
    ansible_connection: httpapi
  tasks:
    - name: "Enable ip routing"
      arista.eos.eos_config:
        lines:
          - ip routing

    - name: "Set up OSPF config"
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              point_to_point: true
              adjacency:
                exchange_start:
                  threshold: 20045623
              max_lsa:
                count: 8000
                ignore_count: 3
                ignore_time: 6
                reset_time: 20
                threshold: 40
              networks:
                - area: "0.0.0.0"
                  prefix: 10.16.0.0/24
                - area: "0.0.0.0"
                  prefix: 10.16.1.0/24
                - area: "0.0.0.0"
                  prefix: 10.16.2.0/23
                - area: "0.0.0.0"
                  prefix: 10.16.4.0/24
              redistribute:
                - routes: "connected"
              router_id: "{{ global.ospf_router_id[inventory_hostname] }}"